DROP TABLE IF EXISTS FLOWERS;

CREATE TABLE FLOWERS (
  flowerId INTEGER AUTO_INCREMENT  PRIMARY KEY,
  flowerName VARCHAR(30),
  noOfFlowers INTEGER,
  costOfFlowers INTEGER,
  discount INTEGER
);

Select * from FLOWERS;